AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  creditcard-validation-api

  Sample SAM Template for creditcard-validation-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  CreditCardValidationApi:
   Type: AWS::Serverless::Api
   Properties:
     StageName: Prod
     Cors:
       AllowMethods: "'GET,POST,OPTIONS,PUT,PATCH,DELETE'"
       AllowHeaders: "'content-type'"
       AllowOrigin: "'*'"
       AllowCredentials: "'*'"
  CreditCardValidationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CreditCardValidationFunction
      Handler: santosh.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        CreditCardValidation:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /creditcard-validate
            Method: get
            RequestParameters: ['method.request.querystring.number']
            RestApiId: !Ref CreditCardValidationApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreditCardValidationApi:
    Description: "API Gateway endpoint URL for Prod stage for Credit Card Validation function"
    Value: !Sub "https://${CreditCardValidationApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CreditCardValidationFunction:
    Description: "CreditCardValidation Lambda Function ARN"
    Value: !GetAtt CreditCardValidationFunction.Arn
  CreditCardValidationFunctionIamRole:
    Description: "Implicit IAM Role created for CreditCardValidation function"
    Value: !GetAtt CreditCardValidationFunctionRole.Arn
